# Preface {.unnumbered}

From natural disasters to human alterations in urban infrastructure,
network connectivity is key for the population\'s survival and for the
metapopulation dynamics ([Alberti 2008](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-alberti_advances_2008)). Through networks, people, resources, goods, information or services flows ([Heywood, Cornelius, and Carver 2011](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-heywood_introduction_2011)), and its spread is highly dependent on those segments with higher betweenness edge centrality ([Kolaczyk and Csárdi 2014](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-kolaczyk_statistical_2014)).
Therefore, measuring the betweenness edge centrality on the different
segments of the network help us to identify critical infrastructures
that play a key role in the connectivity ensuring the movement along the
network.

An interruption of the flow on these critical infrastructures can
induce cascading effects causing physical, social or economic disruption
([Petricola et al. 2022](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-petricola_assessing_2022-1)).
Discrete events such as disasters can trigger these cascading events
disrupting the landscape. These disruptions that test the system\'s
capacity to recover from the change, namely, its resilience ([Scheffer 2009](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-levin_iii17_2009-1)),
can derive from climate change. Extreme events related to climate
change such as storms or floods are being increased as well as the
severity and frequency of most hazards ([Kuffer et al. 2021](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-kuffer_eo-based_2021)).
To minimize the humanitarian consequences of these severe events, the
ability of disaster preparedness by finding criticality of
infrastructure is key ([Petricola et al. 2022](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-petricola_assessing_2022-1)).

As ecosystem services become more stressed in the future ([Costanza et al. 1997](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-costanza_value_1997)),
and the frequency and intensity of extreme natural hazards increases
(\"Summary for Policymakers,\" 2023), increasing resilience is of critical
importance for numerous frameworks. On a global scale, the Sendai
Framework for Disaster Risk Reduction 1 aims to reduce disaster damage
to critical infrastructure and disruption of basic services as part of
the fourth global target. Likewise, (a) damage to critical
infrastructure and (b) number of disruptions to basic services,
attributed to disasters are part of the indicators 11.5.3 from the
Sustainable Development Goal 11, \"making cities and human settlements
inclusive, safe, resilient and sustainable2\". Therefore, both frameworks
aim to increase urban resilience ([Etinay, Egbu, and Murray 2018](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-etinay_building_2018)).

Resilience is a term with different interpretations depending on the discipline ([Therias and Rafiee 2023](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-therias_city_2023-1)).
For example, in ecology, resilience is defined as \"the capacity of a
system to recover to essentially the same state after a disturbance\" ([Scheffer 2009](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-levin_iii17_2009-1)).
In the context of this research, urban resilience is defined as \"a
property of the urban system that enables it to survive and thrive in
the face of uncertainty, adversity, and change\" ([Abenayake et al. 2022a](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-abenayake_innovative_2022)).
Finding critical infrastructures can increase urban resilience by
localizing where to build alternative routes to healthcare facilities
(i.e., increasing redundancy) or finding structures, such as bridges,
that have an important function in the network due to its connectivity
(i.e., increasing robustness). Redundancy and robustness are two
properties of the popular 4R model of resilience, which also includes
resourcefulness and rapidity ([Xu et al. 2024](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-xu_development_2024)).

On a regional level, territorial resilience is one of the main themes
in the EU R&I policy agenda for Nature-based Solutions. Resilience
to natural disasters and adaptation to climate change are part of the
future priorities defined in the Granada Declaration. On a national
level, low-income countries with fewer resources to prepare, mitigate,
and recover from climate change-related disasters, especially the
population living in deprived areas, could benefit from this route
service adapted to disaster management.

Centrality analyses are constrained by its high computational costs,
challenging their validity to represent real-world scenarios. To reduce
these costs, studies did not use entire city- regions as area of
interest ([Abenayake et al. 2022b](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-abenayake_innovative_2022-1)) Similarly, other studies on accessibility used different techniques to maximize computation efficiency ([Spangler et al. 2023](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-spangler_calculating_2023-1)). Likewise, only a selection of the nodes was used to save computation time ([Florath, Chanussot, and Keller 2024](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-florath_road_2024)).
Large spatial scales refined this strategy using network percolation,
which allowed the study of flood disturbances on vast regions such as
the entire road networks of China and the USA, among others ([Van Ginkel et al. 2022](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-van_ginkel_will_2022)). Currently, there are methods and technologies that aim to optimize queries reducing its computational costs.

Spatial indexing systems are used to query large geospatial data
sets, increasing their efficient queries. For example, Uber\'s Hexagonal
Hierarchical Spatial Index (H3) was applied to optimize emergency
response routes ([Diallo et al. 2023](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-diallo_using_2023-1)).
These spatial indexes can be implemented into PostgreSQL using
pgRouting, which has been previously used to find the shortest path to
healthcare facilities ([Alasadi et al., n.d.](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-alasadi_network_nodate)). Instead of PostgreSQL, other new database management system, such as DuckDB, was used to implement memory optimization ([Kuiper, Boncz, and Muhleisen, n.d.](file:///home/ricardo/heigit_bookdown/_book/index.html#ref-kuiper_robust_nodate)).
Therefore, the current contribution of this research would be applying
these optimization processes running pgRouting to obtain different
centrality and accessibility metrics.
